"""Data models for Sentrix alerts."""

from __future__ import annotations

from datetime import UTC, datetime

from pydantic import BaseModel, Field

from sentrix.models.position import (
    AlertSeverity,
    AlertType,
    DeliveryChannel,
    DerivativePosition,
    PortfolioSnapshot,
)


class Alert(BaseModel):
    """An alert generated by the risk detector + AI analyzer."""

    id: int | None = Field(default=None, description="Database ID (set after persistence)")
    address: str = Field(description="Injective address that triggered the alert")
    alert_type: AlertType
    severity: AlertSeverity
    title: str = Field(description="Short alert title")
    message: str = Field(description="AI-generated natural language explanation")
    recommendation: str | None = Field(
        default=None, description="AI-generated actionable recommendation"
    )
    position: DerivativePosition | None = Field(
        default=None, description="The position that triggered the alert (if applicable)"
    )
    snapshot: PortfolioSnapshot | None = Field(
        default=None, description="Full portfolio snapshot at alert time"
    )
    delivered_via: list[DeliveryChannel] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))

    @property
    def severity_emoji(self) -> str:
        """Emoji for alert severity."""
        return {
            AlertSeverity.LOW: "ℹ️",
            AlertSeverity.MEDIUM: "⚡",
            AlertSeverity.HIGH: "⚠️",
            AlertSeverity.CRITICAL: "🚨",
        }[self.severity]

    @property
    def is_critical(self) -> bool:
        """Whether this alert requires immediate attention."""
        return self.severity in (AlertSeverity.HIGH, AlertSeverity.CRITICAL)


class AlertRule(BaseModel):
    """A user-configured alert rule."""

    alert_type: AlertType
    threshold: float = Field(
        description="Threshold value (e.g., 1.2 for margin ratio, 500 for USD balance change)"
    )
    enabled: bool = Field(default=True)
    cooldown_seconds: int = Field(
        default=300, description="Minimum seconds between duplicate alerts"
    )

    @property
    def description(self) -> str:
        """Human-readable description of this rule."""
        descriptions = {
            AlertType.LIQUIDATION_WARNING: f"Margin ratio below {self.threshold}x",
            AlertType.BALANCE_CHANGE: f"Balance change > ${self.threshold}",
            AlertType.MARGIN_DEGRADATION: f"Margin dropped > {self.threshold}% in 10min",
            AlertType.WHALE_MOVEMENT: f"Movement > ${self.threshold:,.0f}",
        }
        return descriptions.get(self.alert_type, f"{self.alert_type.value} @ {self.threshold}")


class RiskEvent(BaseModel):
    """A raw risk event detected by the detector before AI processing."""

    alert_type: AlertType
    severity: AlertSeverity
    address: str
    position: DerivativePosition | None = None
    snapshot: PortfolioSnapshot | None = None
    raw_data: dict = Field(default_factory=dict)
    detected_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
